### ISSUE TITLE
Should we standardize Node's process global?

### ISSUE THREAD

**Issue by CanadaHonk** [CanadaHonk/proposal-cli-api#4]
Should we standardize Node's `process` global instead of making our own new standardized version?

**Comment by littledan** [comment]
We discussed this in a WinterCG call, and while I personally like the idea of reusing the names and rough semantics of existing APIs where it makes sense, it seems that `process.argv` is not one of these: Node doesn't strip off earlier command-line arguments that are targeting Node itself, and Deno's model of stripping these off is higher-level and preferred. So we should use a new name for this API.

**Comment by CanadaHonk** [comment]
I think we can close this as not being done with agreement from [the WinterCG meeting this week](https://github.com/wintercg/admin/issues/61). If someone thinks this should still be done instead, we can reopen.

**Comment by ljharb** [comment]
That doesn't argue against having `process` itself, just having `process.argv`.
